name: Build kubernetes-python-client

# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
on:
  push:
    branches:
      - main
    paths:
      - kubernetes-python-client/**
  pull_request:
    branches:
      - main
    paths:
      - kubernetes-python-client/**

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Kubernetes Python Client
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v5
        with:
          context: kubernetes-python-client
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ryan4yin/kunbernates-python-client:latest
